
package de.unitymedia.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UNDocumentService", targetNamespace = "http://webservice.unitymedia.de", wsdlLocation = "file:/C:/JAX_WSD/UNDocumentService.wsdl")
public class UNDocumentService
    extends Service
{

    private final static URL UNDOCUMENTSERVICE_WSDL_LOCATION;
    private final static WebServiceException UNDOCUMENTSERVICE_EXCEPTION;
    private final static QName UNDOCUMENTSERVICE_QNAME = new QName("http://webservice.unitymedia.de", "UNDocumentService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/JAX_WSD/UNDocumentService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        UNDOCUMENTSERVICE_WSDL_LOCATION = url;
        UNDOCUMENTSERVICE_EXCEPTION = e;
    }

    public UNDocumentService() {
        super(__getWsdlLocation(), UNDOCUMENTSERVICE_QNAME);
    }

    public UNDocumentService(WebServiceFeature... features) {
        super(__getWsdlLocation(), UNDOCUMENTSERVICE_QNAME, features);
    }

    public UNDocumentService(URL wsdlLocation) {
        super(wsdlLocation, UNDOCUMENTSERVICE_QNAME);
    }

    public UNDocumentService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, UNDOCUMENTSERVICE_QNAME, features);
    }

    public UNDocumentService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UNDocumentService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UNDocumentServicePortType
     */
    @WebEndpoint(name = "UNDocumentServiceHttpsSoap11Endpoint")
    public UNDocumentServicePortType getUNDocumentServiceHttpsSoap11Endpoint() {
        return super.getPort(new QName("http://webservice.unitymedia.de", "UNDocumentServiceHttpsSoap11Endpoint"), UNDocumentServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UNDocumentServicePortType
     */
    @WebEndpoint(name = "UNDocumentServiceHttpsSoap11Endpoint")
    public UNDocumentServicePortType getUNDocumentServiceHttpsSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.unitymedia.de", "UNDocumentServiceHttpsSoap11Endpoint"), UNDocumentServicePortType.class, features);
    }

    /**
     * 
     * @return
     *     returns UNDocumentServicePortType
     */
    @WebEndpoint(name = "UNDocumentServiceHttpsSoap12Endpoint")
    public UNDocumentServicePortType getUNDocumentServiceHttpsSoap12Endpoint() {
        return super.getPort(new QName("http://webservice.unitymedia.de", "UNDocumentServiceHttpsSoap12Endpoint"), UNDocumentServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UNDocumentServicePortType
     */
    @WebEndpoint(name = "UNDocumentServiceHttpsSoap12Endpoint")
    public UNDocumentServicePortType getUNDocumentServiceHttpsSoap12Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.unitymedia.de", "UNDocumentServiceHttpsSoap12Endpoint"), UNDocumentServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (UNDOCUMENTSERVICE_EXCEPTION!= null) {
            throw UNDOCUMENTSERVICE_EXCEPTION;
        }
        return UNDOCUMENTSERVICE_WSDL_LOCATION;
    }

}
