
package de.unitymedia.webservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UNDocumentServicePortType", 
targetNamespace = "http://webservice.unitymedia.de")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UNDocumentServicePortType {


    /**
     * 
     * @param applicationId
     * @return
     *     returns java.util.List<de.unitymedia.webservice.LookupPair>
     */
    @WebMethod(action = "urn:productLookup")
    @WebResult(targetNamespace = "http://webservice.unitymedia.de/xsd")
    @RequestWrapper(localName = "productLookup", targetNamespace = "http://webservice.unitymedia.de/xsd", className = "de.unitymedia.webservice.ProductLookup")
    @ResponseWrapper(localName = "productLookupResponse", targetNamespace = "http://webservice.unitymedia.de/xsd", className = "de.unitymedia.webservice.ProductLookupResponse")
    public List<LookupPair> productLookup(
        @WebParam(name = "applicationId", targetNamespace = "http://webservice.unitymedia.de/xsd")
        String applicationId);

    /**
     * 
     * @return
     *     returns de.unitymedia.webservice.GetVersionResponse
     */
    @WebMethod(action = "urn:getVersion")
    @WebResult(name = "getVersionResponse", targetNamespace = "http://webservice.unitymedia.de/xsd", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GetVersionResponse getVersion();

    /**
     * 
     * @param product
     * @param applicationId
     * @return
     *     returns java.util.List<de.unitymedia.webservice.LookupPair>
     */
    @WebMethod(action = "urn:typeLookup")
    @WebResult(targetNamespace = "http://webservice.unitymedia.de/xsd")
    @RequestWrapper(localName = "typeLookup", targetNamespace = "http://webservice.unitymedia.de/xsd", className = "de.unitymedia.webservice.TypeLookup")
    @ResponseWrapper(localName = "typeLookupResponse", targetNamespace = "http://webservice.unitymedia.de/xsd", className = "de.unitymedia.webservice.TypeLookupResponse")
    public List<LookupPair> typeLookup(
        @WebParam(name = "applicationId", targetNamespace = "http://webservice.unitymedia.de/xsd")
        String applicationId,
        @WebParam(name = "product", targetNamespace = "http://webservice.unitymedia.de/xsd")
        String product);

    /**
     * 
     * @param applicationId
     * @return
     *     returns java.util.List<de.unitymedia.webservice.LookupPair>
     */
    @WebMethod(action = "urn:priorityLookup")
    @WebResult(targetNamespace = "http://webservice.unitymedia.de/xsd")
    @RequestWrapper(localName = "priorityLookup", targetNamespace = "http://webservice.unitymedia.de/xsd", className = "de.unitymedia.webservice.PriorityLookup")
    @ResponseWrapper(localName = "priorityLookupResponse", targetNamespace = "http://webservice.unitymedia.de/xsd", className = "de.unitymedia.webservice.PriorityLookupResponse")
    public List<LookupPair> priorityLookup(
        @WebParam(name = "applicationId", targetNamespace = "http://webservice.unitymedia.de/xsd")
        String applicationId);

    /**
     * 
     * @param request
     * @return
     *     returns de.unitymedia.webservice.Response
     */
    @WebMethod(action = "urn:closeActivities")
    @WebResult(targetNamespace = "http://webservice.unitymedia.de/xsd")
    @RequestWrapper(localName = "closeActivities", targetNamespace = "http://webservice.unitymedia.de/xsd", className = "de.unitymedia.webservice.CloseActivities")
    @ResponseWrapper(localName = "closeActivitiesResponse", targetNamespace = "http://webservice.unitymedia.de/xsd", className = "de.unitymedia.webservice.CloseActivitiesResponse")
    public Response closeActivities(
        @WebParam(name = "request", targetNamespace = "http://webservice.unitymedia.de/xsd")
        Request request);

    /**
     * 
     * @param applicationId
     * @return
     *     returns java.util.List<de.unitymedia.webservice.LookupPair>
     */
    @WebMethod(action = "urn:stateLookup")
    @WebResult(targetNamespace = "http://webservice.unitymedia.de/xsd")
    @RequestWrapper(localName = "stateLookup", targetNamespace = "http://webservice.unitymedia.de/xsd", className = "de.unitymedia.webservice.StateLookup")
    @ResponseWrapper(localName = "stateLookupResponse", targetNamespace = "http://webservice.unitymedia.de/xsd", className = "de.unitymedia.webservice.StateLookupResponse")
    public List<LookupPair> stateLookup(
        @WebParam(name = "applicationId", targetNamespace = "http://webservice.unitymedia.de/xsd")
        String applicationId);

    /**
     * 
     * @param request
     * @return
     *     returns de.unitymedia.webservice.Response
     */
    @WebMethod(action = "urn:requestDocumentDuplicate")
    @WebResult(targetNamespace = "http://webservice.unitymedia.de/xsd")
    @RequestWrapper(localName = "requestDocumentDuplicate", targetNamespace = "http://webservice.unitymedia.de/xsd", className = "de.unitymedia.webservice.RequestDocumentDuplicate")
    @ResponseWrapper(localName = "requestDocumentDuplicateResponse", targetNamespace = "http://webservice.unitymedia.de/xsd", className = "de.unitymedia.webservice.RequestDocumentDuplicateResponse")
    public Response requestDocumentDuplicate(
        @WebParam(name = "request", targetNamespace = "http://webservice.unitymedia.de/xsd")
        Request request);

    /**
     * 
     * @return
     *     returns de.unitymedia.webservice.GetServiceProviderResponse
     */
    @WebMethod(action = "urn:getServiceProvider")
    @WebResult(name = "getServiceProviderResponse", targetNamespace = "http://webservice.unitymedia.de/xsd", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GetServiceProviderResponse getServiceProvider();

    /**
     * 
     * @param request
     * @return
     *     returns de.unitymedia.webservice.Response
     */
    @WebMethod(action = "urn:getAllDocuments")
    @WebResult(targetNamespace = "http://webservice.unitymedia.de/xsd")
    @RequestWrapper(localName = "getAllDocuments", targetNamespace = "http://webservice.unitymedia.de/xsd", className = "de.unitymedia.webservice.GetAllDocuments")
    @ResponseWrapper(localName = "getAllDocumentsResponse", targetNamespace = "http://webservice.unitymedia.de/xsd", className = "de.unitymedia.webservice.GetAllDocumentsResponse")
    public Response getAllDocuments(
        @WebParam(name = "request", targetNamespace = "http://webservice.unitymedia.de/xsd")
        Request request);

    /**
     * 
     * @param request
     * @return
     *     returns de.unitymedia.webservice.Response
     */
    @WebMethod(action = "urn:getDocument")
    @WebResult(targetNamespace = "http://webservice.unitymedia.de/xsd")
    @RequestWrapper(localName = "getDocument", targetNamespace = "http://webservice.unitymedia.de/xsd", className = "de.unitymedia.webservice.GetDocument")
    @ResponseWrapper(localName = "getDocumentResponse", targetNamespace = "http://webservice.unitymedia.de/xsd", className = "de.unitymedia.webservice.GetDocumentResponse")
    public Response getDocument(
        @WebParam(name = "request", targetNamespace = "http://webservice.unitymedia.de/xsd")
        Request request);

    /**
     * 
     * @param request
     * @return
     *     returns de.unitymedia.webservice.Response
     */
    @WebMethod(action = "urn:getInboxDocuments")
    @WebResult(targetNamespace = "http://webservice.unitymedia.de/xsd")
    @RequestWrapper(localName = "getInboxDocuments", targetNamespace = "http://webservice.unitymedia.de/xsd", className = "de.unitymedia.webservice.GetInboxDocuments")
    @ResponseWrapper(localName = "getInboxDocumentsResponse", targetNamespace = "http://webservice.unitymedia.de/xsd", className = "de.unitymedia.webservice.GetInboxDocumentsResponse")
    public Response getInboxDocuments(
        @WebParam(name = "request", targetNamespace = "http://webservice.unitymedia.de/xsd")
        Request request);

    /**
     * 
     * @param request
     * @return
     *     returns de.unitymedia.webservice.Response
     */
    @WebMethod(action = "urn:changeDocuments")
    @WebResult(name = "response", targetNamespace = "http://webservice.unitymedia.de/xsd")
    @RequestWrapper(localName = "changeDocuments", targetNamespace = "http://webservice.unitymedia.de/xsd", className = "de.unitymedia.webservice.ChangeDocuments")
    @ResponseWrapper(localName = "changeDocumentsResponse", targetNamespace = "http://webservice.unitymedia.de/xsd", className = "de.unitymedia.webservice.ChangeDocumentsResponse")
    public Response changeDocuments(
        @WebParam(name = "request", targetNamespace = "http://webservice.unitymedia.de/xsd")
        Request request);

    /**
     * Returns the audit trial of the requested document
     * 
     * 			
     * 
     * @param request
     * @return
     *     returns de.unitymedia.webservice.Response
     */
    @WebMethod(action = "urn:getDocumentAuditTrail")
    @WebResult(name = "response", targetNamespace = "http://webservice.unitymedia.de/xsd")
    @RequestWrapper(localName = "getDocumentAuditTrail", targetNamespace = "http://webservice.unitymedia.de/xsd", className = "de.unitymedia.webservice.GetDocumentAuditTrail")
    @ResponseWrapper(localName = "getDocumentAuditTrailResponse", targetNamespace = "http://webservice.unitymedia.de/xsd", className = "de.unitymedia.webservice.GetDocumentAuditTrailResponse")
    public Response getDocumentAuditTrail(
        @WebParam(name = "request", targetNamespace = "http://webservice.unitymedia.de/xsd")
        Request request);

    /**
     * 
     * @param parameters
     * @return
     *     returns de.unitymedia.webservice.GetOptInCorrespondenciesResult
     */
    @WebMethod(action = "getOptInCorrespondencies")
    @WebResult(name = "getOptInCorrespondenciesResult", targetNamespace = "http://webservice.unitymedia.de/xsd", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GetOptInCorrespondenciesResult getOptInCorrespondencies(
        @WebParam(name = "getOptInCorrespondenciesParameter", targetNamespace = "http://webservice.unitymedia.de/xsd", partName = "parameters")
        GetOptInCorrespondenciesParameter parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns de.unitymedia.webservice.UpdateOptInCorrespondenciesResult
     */
    @WebMethod(action = "updateOptInCorrespondency")
    @WebResult(name = "updateOptInCorrespondenciesResult", targetNamespace = "http://webservice.unitymedia.de/xsd", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public UpdateOptInCorrespondenciesResult updateOptInCorrespondency(
        @WebParam(name = "updateOptInCorrespondenciesParameter", targetNamespace = "http://webservice.unitymedia.de/xsd", partName = "parameters")
        UpdateOptInCorrespondenciesParameter parameters);

    /**
     * 
     * @param request
     * @return
     *     returns de.unitymedia.webservice.Response
     */
    @WebMethod(action = "urn:getCorrespondencyDocuments")
    @WebResult(targetNamespace = "http://webservice.unitymedia.de/xsd")
    @RequestWrapper(localName = "getCorrespondencyDocuments", targetNamespace = "http://webservice.unitymedia.de/xsd", className = "de.unitymedia.webservice.GetCorrespondencyDocuments")
    @ResponseWrapper(localName = "getCorrespondencyDocumentsResponse", targetNamespace = "http://webservice.unitymedia.de/xsd", className = "de.unitymedia.webservice.GetCorrespondencyDocumentsResponse")
    public Response getCorrespondencyDocuments(
        @WebParam(name = "request", targetNamespace = "http://webservice.unitymedia.de/xsd")
        Request request);

    /**
     * 
     * @param request
     * @return
     *     returns de.unitymedia.webservice.Response
     */
    @WebMethod(action = "urn:getCorrespondencyDocumentsCount")
    @WebResult(targetNamespace = "http://webservice.unitymedia.de/xsd")
    @RequestWrapper(localName = "getCorrespondencyDocumentsCount", targetNamespace = "http://webservice.unitymedia.de/xsd", className = "de.unitymedia.webservice.GetCorrespondencyDocumentsCount")
    @ResponseWrapper(localName = "getCorrespondencyDocumentsCountResponse", targetNamespace = "http://webservice.unitymedia.de/xsd", className = "de.unitymedia.webservice.GetCorrespondencyDocumentsCountResponse")
    public Response getCorrespondencyDocumentsCount(
        @WebParam(name = "request", targetNamespace = "http://webservice.unitymedia.de/xsd")
        Request request);

    /**
     * 
     * @param request
     * @return
     *     returns de.unitymedia.webservice.Response
     */
    @WebMethod(action = "urn:getOrders")
    @WebResult(targetNamespace = "http://webservice.unitymedia.de/xsd")
    @RequestWrapper(localName = "getOrders", targetNamespace = "http://webservice.unitymedia.de/xsd", className = "de.unitymedia.webservice.GetOrders")
    @ResponseWrapper(localName = "getOrdersResponse", targetNamespace = "http://webservice.unitymedia.de/xsd", className = "de.unitymedia.webservice.GetOrdersResponse")
    public Response getOrders(
        @WebParam(name = "request", targetNamespace = "http://webservice.unitymedia.de/xsd")
        Request request);

    /**
     * 
     * @param request
     * @return
     *     returns de.unitymedia.webservice.Response
     */
    @WebMethod(action = "urn:lockDocument")
    @WebResult(targetNamespace = "http://webservice.unitymedia.de/xsd")
    @RequestWrapper(localName = "lockDocument", targetNamespace = "http://webservice.unitymedia.de/xsd", className = "de.unitymedia.webservice.LockDocument")
    @ResponseWrapper(localName = "lockDocumentResponse", targetNamespace = "http://webservice.unitymedia.de/xsd", className = "de.unitymedia.webservice.LockDocumentResponse")
    public Response lockDocument(
        @WebParam(name = "request", targetNamespace = "http://webservice.unitymedia.de/xsd")
        Request request);

    /**
     * 
     * @param request
     * @return
     *     returns de.unitymedia.webservice.Response
     */
    @WebMethod(action = "urn:unlockDocument")
    @WebResult(targetNamespace = "http://webservice.unitymedia.de/xsd")
    @RequestWrapper(localName = "unlockDocument", targetNamespace = "http://webservice.unitymedia.de/xsd", className = "de.unitymedia.webservice.UnlockDocument")
    @ResponseWrapper(localName = "unlockDocumentResponse", targetNamespace = "http://webservice.unitymedia.de/xsd", className = "de.unitymedia.webservice.UnlockDocumentResponse")
    public Response unlockDocument(
        @WebParam(name = "request", targetNamespace = "http://webservice.unitymedia.de/xsd")
        Request request);

    /**
     * 
     * @param request
     * @return
     *     returns de.unitymedia.webservice.Response
     */
    @WebMethod(action = "urn:getCorrespondencyDocumentsWithLock")
    @WebResult(targetNamespace = "http://webservice.unitymedia.de/xsd")
    @RequestWrapper(localName = "getCorrespondencyDocumentsWithLock", targetNamespace = "http://webservice.unitymedia.de/xsd", className = "de.unitymedia.webservice.GetCorrespondencyDocumentsWithLock")
    @ResponseWrapper(localName = "getCorrespondencyDocumentsWithLockResponse", targetNamespace = "http://webservice.unitymedia.de/xsd", className = "de.unitymedia.webservice.GetCorrespondencyDocumentsWithLockResponse")
    public Response getCorrespondencyDocumentsWithLock(
        @WebParam(name = "request", targetNamespace = "http://webservice.unitymedia.de/xsd")
        Request request);

}
